version: '3'
services:
  xbdd:
    container_name: xbdd
    build: ./packager
    ports:
      - "80:80"
      - "443:443"
  mongo:
    container_name: xbdd_mongo
    build: ./mongo
    ports:
      - "27017:27017"
