version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/frontend'
    update_schedule: 'weekly'
    ignored_updates:
      - match:
          dependency_name: 'prettier'
          version_requirement: '^2.0.0'
  - package_manager: 'java:maven'
    directory: '/frontend'
    update_schedule: 'weekly'
  - package_manager: 'java:maven'
    directory: '/backend'
    update_schedule: 'weekly'
    ignored_updates:
      - match:
          dependency_name: 'org.springframework.boot:spring-boot-maven-plugin'
      - match:
          dependency_name: 'org.springframework.boot:spring-boot-dependencies'
