spring:
  data:
    mongodb:
      username: admin
      password: password
      host: localhost
      port: 27017
      authentication-database: admin

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          # facebook:
          #   client-id: your-app-client-id
          #   client-secret: your-app-client-secret
          # okta:
          #   client-id: your-app-client-id
          #   client-secret: your-app-client-secret

  ldap:
    embedded:
      base-dn: dc=springframework,dc=org
      ldif: classpath:test-server.ldif
      port: 8389

# Enable this if you want to run on https, note that the frontend .env files will need to be updated
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:certs/keystore.p12
#    key-store-password: password

logging.level:
  org.springframework.security: DEBUG
