github:
  client:
    id: <put your github app id here>
    secret: <put your github app secret here>

spring:
  data:
    mongodb:
      username: admin
      password: password
      host: localhost
      port: 27017
      authentication-database: admin

security:
  oauth2:
    client:
      client-id: xbdd
      client-secret: secret
      accessTokenUri: http://localhost:8080/oauth/token

# Enable this if you want to run on https, note that the frontend .env files will need to be updated
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:certs/keystore.p12
#    key-store-password: password

logging.level:
  org.springframework.security: DEBUG
